version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
      - SESSION_SECRET=${SESSION_SECRET:-development_secret_key_12345}
      - DATABASE_URL=sqlite:///instance/chatgpt_app.db
    volumes:
      - ./instance:/app/instance
      - ./token.json:/app/token.json:rw
    restart: unless-stopped